---
# Default variables for runner_setup role
runner_setup_github_owner: "thomas-enj"
runner_setup_github_repo: "appbaq-infra-terraform"
# This token will be dynamically provided by the CI pipeline
runner_setup_github_token: "PLACEHOLDER_TOKEN"